### ISSUE TITLE
Link to iNat pages

### ISSUE THREAD

**Issue by laurawalexander** [matthewkling/natlas#20]
@matthewkling  Should I retrieve the iNat IDs for all of the taxonomic levels for that tonight? 
Pros: if it's working for tomorrow, that would be cool 
Cons: significantly increased risk of computer and/or my patience with slow computer crashing

**Comment by matthewkling** [comment]
@laurawalexander totally your call, I don't know the seriousness of the computer crashing problems. Should be easy to integrate once it's ready, but it's not top priority for sure. I'm assigning this to you for now; once the data is added to the csv, you can assign it back to me and I'll add it to the visualization.

**Comment by matthewkling** [comment]
@laurawalexander Thanks for adding the species IDs to the observation file. Do taxa higher than species also have IDs? If so, can we add them to the taxonomy table in the same way we added common names?  That would allow us to display a link for whatever taxon was selected, rather than when only a leaf-level species is selected.

**Comment by laurawalexander** [comment]
Yes, the species list file has (PORE|GOGA_species_list.csv) have a column for each rank called rank.inat.ID, just like they have rank.common and rank.science. Pasting "http://www.inaturalist.org/taxa/" and an id number will gives you a usable link.
